script:
- git remote add upstream https://github.com/alliedmodders/sourcemod.git
- git fetch upstream master
- echo -e "machine github.com\nlogin $(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)\npassword $GITHUB_TOKEN" >> ~/.netrc
- git push origin upstream/master:master
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
